apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: wordpress
  labels:
      app: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    imagePullPolicy: Always
    ports:
      - containerPort: 3306
        name: mysql-pod-port
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_DATABASE
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-db
    resources:
      requests:
        cpu: 0.5       
        memory: 1Gi
      limits:
        cpu: 1    
        memory: 1.3Gi
  restartPolicy: Always
  volumes:
    - name: mysql-db
      hostPath:
        path: /var/lib/mysql