apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: wordpress
spec:
  selector:
    app: nginx-pod
  ports:
    - port: 8888
      targetPort: 80
  type: LoadBalancer 