apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress
  labels:
      app: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-pod
  template:
      metadata:
        labels:
          app: wordpress-pod
      spec:
        containers:
        - name: wordpress
          image: wordpress:latest
          imagePullPolicy: Always
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              cpu: 100m       
              memory: 200Mi
            limits:
              cpu: 200m    
              memory: 200Mi
        restartPolicy: Always