apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: my-secret-1
data:
{{ (.Files.Glob "secret/*").AsSecrets | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: my-secret-2
data:
  login.txt: |-
    {{ .Files.Get "secret/login.txt" | b64enc }}